server:
  port: ${PORT:9091}
  error:
    include-binding-errors: always
    include-message: always
    include-exception: true
spring:
  data:
    mongodb:
      uri: mongodb+srv://test_user123456:4hRsOKoJxkHswunQ@cluster0.nbzfi.mongodb.net/demo

todo-client:
  base-url: https://jsonplaceholder.typicode.com